import type React from "react"
import * as LucideIcons from "lucide-react"

// List of available icons for the picker
export const AVAILABLE_ICONS = [
  "Building2",
  "Users",
  "FileText",
  "Briefcase",
  "Calendar",
  "Settings",
  "Mail",
  "Phone",
  "MapPin",
  "Globe",
  "Search",
  "Filter",
  "TrendingUp",
  "Award",
  "Crown",
  "Rocket",
  "Zap",
  "Sparkles",
  "Heart",
  "Star",
  "Target",
  "CheckCircle",
  "Shield",
  "Lock",
  "Key",
  "Database",
  "Server",
  "Cloud",
  "Code",
  "Terminal",
  "Package",
  "Layers",
  "Grid3x3",
  "FolderTree",
  "Folder",
  "File",
  "Image",
  "Video",
  "Music",
  "Headphones",
  "Mic",
  "Camera",
  "Printer",
  "Monitor",
  "Smartphone",
  "Tablet",
  "Laptop",
  "Watch",
  "Wifi",
  "Bluetooth",
  "Battery",
  "Plug",
  "Lightbulb",
  "Home",
  "Store",
  "ShoppingCart",
  "CreditCard",
  "DollarSign",
  "TrendingDown",
  "BarChart",
  "PieChart",
  "Activity",
  "Clipboard",
  "ClipboardCheck",
  "BookOpen",
  "GraduationCap",
  "Bookmark",
  "Tag",
  "Flag",
  "Bell",
  "MessageSquare",
  "MessageCircle",
  "Send",
  "Inbox",
  "Archive",
  "Trash2",
  "Edit",
  "Plus",
  "Minus",
  "X",
  "Check",
  "ChevronRight",
  "ChevronLeft",
  "ChevronUp",
  "ChevronDown",
  "ArrowRight",
  "ArrowLeft",
  "ArrowUp",
  "ArrowDown",
  "RefreshCw",
  "RotateCw",
  "Download",
  "Upload",
  "Share2",
  "Link",
  "ExternalLink",
  "Eye",
  "EyeOff",
  "Info",
  "AlertCircle",
  "AlertTriangle",
  "HelpCircle",
  "MoreHorizontal",
  "MoreVertical",
  "Menu",
  "Maximize",
  "Minimize",
  "Copy",
  "Scissors",
  "Paperclip",
] as const

export type IconName = (typeof AVAILABLE_ICONS)[number]

// Render an icon from its string name
export function renderIcon(iconName: string, props?: React.ComponentProps<LucideIcons.LucideIcon>) {
  const Icon = (LucideIcons as any)[iconName] as LucideIcons.LucideIcon

  if (!Icon) {
    // Fallback to a default icon if the name is not found
    return <LucideIcons.HelpCircle {...props} />
  }

  return <Icon {...props} />
}
